#!/bin/bash

run_additional() {
cat <<EOT

Additional software to install from AppStore

  1Password
  Airmail
  DaisyDisk
  iStat Mini
  Pixelmator
  Slack
  Unarchiver
  Xcode
  Numbers
  Keynote
  Pages

EOT

}
