#!/bin/bash

# Install Visual Studio Code plugins

run_code() {
  local -a extensions=(
    'EditorConfig.EditorConfig'
    'Orta.vscode-jest'
    'Zignd.html-css-class-completion'
    'bierner.color-info'
    'chenxsan.vscode-standardjs'
    'christian-kohler.npm-intellisense'
    'christian-kohler.path-intellisense'
    'clinyong.vscode-css-modules'
    'cpylua.language-postcss'
    'dsznajder.es7-react-js-snippets'
    'dzannotti.vscode-babel-coloring'
    'esbenp.prettier-vscode'
    'jock.svg'
    'joelday.docthis'
    'robertohuertasm.vscode-icons'
    'shinnn.stylelint'
    'teabyii.ayu'
    'waderyan.gitblame'
    'whizkydee.material-palenight-theme'
    'xabikos.JavaScriptSnippets'
    'xabikos.ReactSnippets'
  )

  # Ask before installing extensions
  seek_confirmation "Do you want to install these vscode extensions?"

  if is_confirmed; then
      for i in "${extensions[@]}"
      do
        code --install-extension $i
      done
      e_success "Software installed"
  else
      printf "Skipped installing extensions.\n"
  fi
}
