#!/bin/bash

# Install Visual Studio Code plugins

run_code() {
  local -a extensions=(
    'teabyii.ayu'
    'dzannotti.vscode-babel-coloring'
    'xabikos.JavaScriptSnippets'
    'chenxsan.vscode-standard-format'
    'chenxsan.vscode-standardjs'
    'christian-kohler.npm-intellisense'
    'christian-kohler.path-intellisense'
    'TimonVS.ReactSnippetsStandard'
    'shinnn.stylelint'
    'ms-vscode.sublime-keybindings'
    'robertohuertasm.vscode-icons'
  )

  # Ask before installing extensions
  seek_confirmation "Do you want to install these vscode extensions?"

  if is_confirmed; then
      for i in "${extensions[@]}"
      do
        code --install-extension $i
      done
      e_success "Software installed"
  else
      printf "Skipped installing extensions.\n"
  fi
}