#!/bin/bash

run_download() {
e_header "Opening pages of third-party applications..."

open https://github.com/adobe-fonts/source-code-pro/releases
open https://www.docker.com/docker-toolbox
open https://www.google.com/intl/de/chrome/browser
open https://imageoptim.com
open https://owncloud.org/install
open http://www.sublimetext.com/3
}
