#!/bin/bash

run_help() {

cat <<EOT
OS X dotfiles - Fabian Gündel

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    -l, --list      Print a list of third-party apps
    -o, --open 	    Open websites of third-party apps in the browser
    --no-packages   Suppress package updates
    --no-sync       Suppress pulling from the remote repository

Documentation can be found at https://github.com/sto3psl/dotfiles/

Copyright (c) Nicolas Gallagher, Fabian Gündel
Licensed under the MIT license.
EOT

}
