#!/bin/bash

run_node() {
	curl -L https://git.io/n-install | N_PREFIX="$HOME/.n" bash -s -- -y latest

	export N_PREFIX="$HOME/.n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

	npm install -g pnpm 
	
	pnpm install -g gitignore serve tldr fkill-cli vercel pure-prompt
}
