#!/bin/bash

run_node() {
	# install nvm
	curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash

	# source nvm
	. ~/.nvm/nvm.sh

	# install latest node version
	nvm install node

	# tell nvm to use latest node version
	nvm use node

	npm install -g npm gitignore serve tldr
}
